language: go

sudo: false

go:
  - 1.7
  - tip

services:
  - redis-server

install:
  - go get -u ./...
  - go get -u github.com/stretchr/testify/assert
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - go test -v -bench=. -benchmem -cover ./...
  - gometalinter --disable-all --enable=aligncheck --enable=deadcode --enable=dupl --enable=errcheck --enable=goconst --enable=goconst --enable=gocyclo --enable=goimports --enable=golint --enable=gosimple --enable=gotype --enable=ineffassign --enable=interfacer --enable=misspell --enable=staticcheck --enable=structcheck --enable=unconvert --enable=unused --enable=varcheck ./... --deadline=1m
  - goveralls -v -service=travis-ci -repotoken=$COVERALLS_TOKEN
